server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
  jpa:
    open-in-view: false
logging:
  level:
    redis.clients: TRACE
    org.springframework.data: TRACE
